-- ByaHero Supabase Schema (Initial Prototype)

-- 1. PROFILES: Shared by Drivers and Commuters
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  username TEXT UNIQUE,
  email TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'commuter' CHECK (role IN ('commuter', 'driver')),
  is_sharing_location BOOLEAN DEFAULT FALSE
);

-- 2. ROUTES: Static paths for Jeepneys
CREATE TABLE routes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL, -- e.g., "Lahug - Guadalupe"
  code TEXT NOT NULL UNIQUE, -- e.g., "04L"
  path_coordinates JSONB NOT NULL -- Array of [lat, lng]
);

-- 3. JEEPNEYS: Active vehicles
CREATE TABLE jeepneys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  driver_id UUID REFERENCES profiles(id) UNIQUE,
  route_id BIGINT REFERENCES routes(id),
  plate_number TEXT UNIQUE,
  is_active BOOLEAN DEFAULT FALSE,
  current_occupancy INTEGER DEFAULT 0
);

-- 4. LOCATIONS: Real-time position tracking
CREATE TABLE locations (
  user_id UUID REFERENCES profiles(id) PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  heading DOUBLE PRECISION DEFAULT 0, -- Direction
  speed DOUBLE PRECISION DEFAULT 0
);

-- Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE jeepneys ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;

-- Public read access for routes and active jeepneys
CREATE POLICY "Public can view routes" ON routes FOR SELECT USING (true);
CREATE POLICY "Public can view active jeepneys" ON jeepneys FOR SELECT USING (is_active = true);
CREATE POLICY "Public can view active locations" ON locations FOR SELECT USING (true);

-- Drivers can update their own location
CREATE POLICY "Users can update their own location" ON locations 
  FOR ALL USING (auth.uid() = user_id);

-- Profiles
CREATE POLICY "Public can view profiles" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert own profile" ON profiles 
  FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles 
  FOR UPDATE USING (auth.uid() = id);

-- Realtime setup
ALTER PUBLICATION supabase_realtime ADD TABLE locations;
ALTER PUBLICATION supabase_realtime ADD TABLE jeepneys;
